config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'devblog', to: 'pages#devblog'
  

     

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < PagesController
  
  
  
  def index
    render layout: 'devblog'
  end
  
  def new
    @article = Article.new
    render layout: 'devblog'
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "article was successfully created"
      redirect_to article_path(@article) 
    else
      render 'new', layout: 'devblog'
    end
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :description)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
  def home
    render layout: 'application'
  end
  
  def devblog
    render layout: 'devblog'
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
articles page

app/views/articles/new.html.erb
create an article

<% if @article.errors.any? %>
  <ul>
    <h2>the following errors prevented the page from being created</h2>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">

    <title><%= content_for?(:title) ? yield(:title) : "Colin Web Design" %></title>

    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', '//fonts.googleapis.com/css?family=Lato:400,300,700', media: 'all', 'data-turbolinks-track' => true %>
  </head>

  <body>
    
    <%= render 'navbar' %>

    <%= yield %>

  </body>
</html>

app/views/layouts/devblog.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">

    <title><%= content_for?(:title) ? yield(:title) : "Colin Web Design" %></title>

    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', 'application_devblog', '//fonts.googleapis.com/css?family=Lato:400,300,700', media: 'all', 'data-turbolinks-track' => true %>
  </head>

  <body>
    
    <% flash.each do |name, msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>
    
    <%= yield %>

  </body>
</html>

app/views/pages/_navbar.html.erb
<header>	
	<nav>
		<div class="nav-bar">
			<div class="row">
			  <%= link_to image_tag("Logo-white.png", class: "logo"), root_path %>
				<div class="nav-links js--nav-links">
					<ul>
						<li><a href="#about">About</a></li>
						<li><a href="#past-projects">Past Projects</a></li>
						<li><a href="#contact">Contact</a></li>
						<li><%= link_to 'Dev Blog', devblog_path %></li>
					</ul>
				</div>
				<a class="mobile-nav-icon js--nav-icon"><i class="ion-navicon-round"></i></a>
			</div>
		</div>
	</nav>			
</header>	

app/views/pages/devblog.html.erb
<div class="row">
  <h2>Dev Blog page</h2>
  <p>hello this is the blog page</p>
</div>

app/views/pages/home.html.erb
<section id="main" class="section-main">
  <div class="row">
    <div class="header-box">
  		<h1>Clean. Efficient.<br>Design Solutions</h1>
  	</div>
		<div class="btn-box">
		  <a href="#about" class="btn-main">Let's Get Started</a>
	  </div>
  	</div>
	</div>
	  <div class="down-arrow">
  	 <h3>&#8675;<h3>
  </div>
</section>

<section id="about" class="section-about js--section-about">
  
  <div class="row">
    <h2>About Me</h2>
    <br>
  </div>
  
  <div class="row">
    <div class="intro-1">
      <p>
        My name is Colin. At the start of 2016 I began to study with the goal to become a full stack web developer.
        I am learning HTML, CSS, Ruby on Rails, and whatever else is nessesary to reach this goal.
        This site is my launch pad, my practice ground, my study guide, and also my resume.
        As I learn, I will test, and implement my new skills and knowledge onto this site.
        Lets see where this journey leads.
      </p>
    </div>
  </div>
        
  <div class="row">
    <p class="intro-2">
      My current learning proccess:  
    </p>
    <div class="large-4 columns">
      <figure class="col-container">
        <i class="ion-ios-book icon-large"></i>
      </figure>
      <p>Study and learn from various online resources. These include Udemy.com, hackerrank.com, and any other tutorials I find.</p>
    </div>
    
    <div class="large-4 columns">
      <figure class="col-container">
        <i class="ion-edit icon-large"></i>
      </figure>
      <p>Apply learnt knowledge into this website. I built this website with the Ruby on Rails framework, using HTML and CSS.
      </br>
      Things that I will need to learn in the near future: <br>
      <ul>
        <li>Bootstrap/Foundation</li>
        <li>SCSS/SASS</li>
        <li>Slim</li>
      </ul>
      </p>
    </div>
    
    <div class="large-4 columns">
      <figure class="col-container">
         <i class="ion-refresh icon-large"></i>
      </figure>
      <p>Change the site as new skills are learnt. Work on other projects using the skills I learnt.</p>
      
    </div>
  </div>
</section>

<section id="past-projects" class="section-past-projects">
  <div class="row">
    <h2>My Past Projects</h2>
    <br>
    <div class="project-contrainer">
      
      <div class="thumbnail">
        <div class="view view-ninth">
        	<%= image_tag("thumbnail-omnifood.png", :alt => "Omnifood") %>
        	<div class="mask mask-1"></div>
        	<div class="mask mask-2"></div>
        	<div class="content">
        		<a href="#" class="info">View&nbsp;&nbsp;&nbsp;<i class="ion-ios-arrow-forward"></i></a>
        	</div>
        </div>
      </div>
      <h4>Omnifood Website</h4>
      <p>
        Omnifood is a fictional company and the website is part the Udemy HTML & CSS course project.
      </p>
    </div>
    
  </div>

</section>

<section id="contact" class="section-contact">
  <div class="accordion" data-accordion data-allow-all-closed="true">
    <div class="accordion-item" data-accordion-item>
      <a class="accordion-title contact-clickable"><i class="ion-ios-email">&nbsp;</i>Contact? <span>Click Me</span></a>
      <div class="accordion-content" data-tab-content>
        <h2>I'd love to hear from you</h2>
        <br>
        <form class="contact-form" data-abide>
          <div class="row">
            <input type="text" id="name" placeholder="name" required>
            <input type="email" id="email" placeholder="your email" required>
              <span class="form-error">
                Please enter a valid email address.
              </span>
            <textarea id="textarea" placeholder="message..." required></textarea>
            <input type="submit" class="btn-form" value="Submit">
          </div>  
        </form>
      </div>
    </div>
  </div>

</section>

<footer>
  <div class="row">
    <ul class="page-links">
      <li><a href="#main">Home</li>
      <li><a href="#about">About</li>
      <li><a href="#past-projects">Past Projects</li>
      <li><%= link_to 'Dev Blog', devblog_path %></li>
    </ul>
    <ul class="social-links">
			<li><a href="#"><i class="ion-social-facebook"></i></a></li>
			<li><a href="#"><i class="ion-social-twitter"></i></a></li>
			<li><a href="#"><i class="ion-social-googleplus"></i></a></li>
			<li><a href="#"><i class="ion-social-instagram"></i></a></li>
    </ul>
  </div>
  <div class="row">
    <p>&copy; 2016 Colin Design Solutions</p>
  </div>
</footer>